services:
  proof-node:
    build:
      context: ./proof-node
      args:
        - SGX=${SGX:-false}
    image: ${SGX:+sgx_}proof_node
    container_name: ${SGX:+sgx_}proof_node
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/aesmd:/var/run/aesmd
      - /mnt/sealed:/mnt/sealed
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
    environment:
      - MAX_VALIDATORS=3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SGX=${SGX:-false}
      - SGX_AESM_ADDR=${SGX_AESM_ADDR:-${SGX:+1}0}
      - IAS_API_KEY=${IAS_API_KEY:-}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    network_mode: bridge