version: '3.8'

services:
  proof-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /var/run/aesmd:/var/run/aesmd
    devices:
      - /dev/sgx_enclave
    environment:
      - SGX_ENABLED=true