services:
  proof-node:
    build:
      context: ./proof-node
    image: proof_node
    container_name: proof_node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/aesmd:/var/run/aesmd
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true  # This might be necessary for SGX operations
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"