version: '3.8'

services:
  flask-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/aesmd:/var/run/aesmd
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      - /dev/sgx_enclave
    environment:
      - SGX_ENABLED=true
    command: python -m proof_node

  aesmd:
    image: intel/aesmd
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd:/var/run/aesmd