services:
  flask-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/aesmd:/var/run/aesmd
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    environment:
      - SGX_ENABLED=true
    privileged: true
    command: sh -c "/opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon & python -m proof_node"