version: '3.8'

services:
  flask_server:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SGX_DEVICE=/dev/sgx/enclave
    devices:
      - /dev/sgx/enclave:/dev/sgx/enclave
    privileged: true

  test_image:
    build:
      context: ./test_image
      dockerfile: Dockerfile
    image: test_image:latest
