services:
  proof-node:
    build: ./proof-node
    image: proof-node
    container_name: proof-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MAX_VALIDATORS=3
      - DOCKER_HOST=unix:///var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
