services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/app/config.yaml
      - ./generic.manifest:/app/generic.manifest
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
    working_dir: /app